apiVersion: v2
description: A Helm chart for the Conference App
name: fmtok8s-conference-chart
version: v0.1.2
type: application
icon: https://salaboy.files.wordpress.com/2019/07/avatar.png
appVersion: 0.1.0
maintainers: 
  - name: salaboy
    email: salaboy@gmail.com
    url: http://salaboy.com
home: http://github.com/salaboy/from-monolith-to-k8s    
keywords:
  - cloudnative
  - example
  - cd
  - kubernetes
  - tutorial
dependencies:
- name: fmtok8s-frontend
  repository: https://salaboy.github.io/helm/
  version: v0.1.1
- name: fmtok8s-agenda-service
  repository: https://salaboy.github.io/helm/
  version: v0.1.2
- name: fmtok8s-c4p-service
  repository: https://salaboy.github.io/helm/
  version: v0.1.1
- name: fmtok8s-email-service
  repository: https://salaboy.github.io/helm/
  version: v0.1.0
- name: kube-prometheus
  repository: https://charts.bitnami.com/bitnami
  condition: prometheus.enabled
  version: 8.0.8
- name: grafana-operator
  repository: https://charts.bitnami.com/bitnami
  version: 2.6.4
  condition: grafana.enabled
- name: grafana-loki
  repository: https://charts.bitnami.com/bitnami
  version: 2.6.2
  condition: loki.enabled
