{{- if .Values.loki.enabled }}
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: loki-datasource
  labels:
    
spec:
  name: grafana-loki.yaml
  datasources:
    - name: Loki
      type: loki
      access: proxy
      url: {{ .Release.Name }}-grafana-loki-gateway:3100
      isDefault: false
      version: 1
      editable: true
{{- end }}